### ISSUE TITLE
Are there any Prerequisites?

### ISSUE THREAD

**Issue by avirlrma** [andri27-ts/60_Days_RL_Challenge#2]
I am sure RL must come with a lot of Prerequisites, can you list them, please? It would really help people like me. :smile_cat:

**Comment by nicolefinnie** [comment]
@andri27-ts  How did you get so many to join this challenge with you? Too cool!

**Comment by andri27-ts** [comment]
@avirlrma sure, I will do it

**Comment by andri27-ts** [comment]
@nicolefinnie I only posted the challenge on ycombinator. It's incredible how many people joined it

**Comment by avirlrma** [comment]
@andri27-ts Thanks! Appreciated.
