### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by zhyongquan** [andri27-ts/60_Days_RL_Challenge#3]
is it ok to translate Chinese?

**Comment by andri27-ts** [comment]
How can you translate the video lectures and the other material?

**Comment by zhyongquan** [comment]
i will try to find Chinese version

**Comment by zhyongquan** [comment]
https://github.com/MLEveryday/60_Days_RL_Challenge
check Chinese version here

**Comment by andri27-ts** [comment]
But the main content is still in English, isn't it? So why translate the other materials?
