### ISSUE TITLE
A2C Suggestion

### ISSUE THREAD

**Issue by MoMe36** [andri27-ts/60_Days_RL_Challenge#6]
Hey, 

Nice work in this repo ! In your A2C example, I think you should: 

1.  Make sure you initialize your agent with small weights
1. As you said, avoid sharing parameters between policy and critic

Good luck !

**Comment by andri27-ts** [comment]
Hi, yes I'm trying with two separate NN, is helping a little bit. Also some parameter tuning is useful. 
Why do you think smaller weights could be helpful?
Thanks!

**Comment by MoMe36** [comment]
Well, I don't know the theoretical reason, but I've seen it regularly on implementations, flagged as good RL pratice. ;)

**Comment by andri27-ts** [comment]
Ok, thanks for the suggestion!! 
Finally, I found out that there is a bug on the indexing of a tensor.
I'll push the correct code soon.
