### ISSUE TITLE
Interested by WorldModels?  

### ISSUE THREAD

**Issue by MoMe36** [andri27-ts/60_Days_RL_Challenge#7]
Hey ! Me again ;) 

I've seen that you plan on using Model-based RL ? Are you planning to go over some agent-imagined world like in this [post](https://worldmodels.github.io) ? 

If so, I just finished a working [VAE implementation](https://github.com/MoMe36/WorldModels) , particularly useful for state representation.

**Comment by andri27-ts** [comment]
Hi! 
Yes, probably something like that but I didn't decide it yet.
I'll keep your implementation in mind.
Thanks!
